### ISSUE TITLE
Save states

### ISSUE THREAD

**Issue by HalosGhost** [rolfmorel/macht#2]
This is an incredibly versatile creation, and I must say, I am deeply impressed. The only thing I find myself wanting is a save state. For example, the ability to pass a particular command-line option on running to resume a saved game.

I imagine only saving one at a time at a simple location like `$HOME/.local/share/macht/state.save`.

The technical requirement would be two fold, the ability for `macht` to start being passed a file that it uses to (re)create the board, and the ability for it to export a file with the same format.

Given the relative simplicity of the game in its current form, I'd recommend this code take the form of a CSV file (filling in blank locations with 0s may make validating such a file simpler).

Do you have any interest in implementing something like this?

**Comment by rolfmorel** [comment]
Hi HalosGhost, great that you're taking an interest in the game.

I think adding a save state feature is a great idea and will start some work on it shortly.

As for how to implement it:
- How would you prefer the commandline interface? Possibly `-c`/`--continue` or maybe rather `-r`/`--resume`. This option would then take one optional argument specifying from which file to resume.
- How would the user specify the file to which the state needs to be saved when starting a new game. Maybe the above should be `-r`/`--resume` and `-s`/`--save` to specify the file.
- I'm not sure that CSV records would work as the game would need to save, in addition to the grid dimensions and tiles, the base number and it's current score. Maybe YAML or JSON would be better suited to storing multiple types of data. Any ideas on this, as I rather like the simplicity of CSV.

**Comment by HalosGhost** [comment]
I think, perhaps instead of having separate resume and save commands, having a `-c|--continuous` flag that would do both (resume the progress as shown in the save file and save the game to the file when done). It would then, take an optional parameter which would be the file with the game to load and the file where the closing save would be written.

If no file path is specified, using something standardized as a default save state location would be much appreciated (e.g., `$XDG_CONFIG_HOME/.config/macht/default.save`). So, if a user were to start `macht` without using the `-c|--continuous` flag/switch, it will be a new game.

As for the file format, I actually think CSV should be doable. I haven't looked into the calculation for the score, but given that the score is based on the tiles, and the tiles would be saved, would it be really difficult to recalculate the score from the tiles on-load?

If the score is not a problem to recalculate, then CSV should be a piece of cake. The whole file would just be the tile positions, e.g.:

```
2048, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
```

Thoughts?

**Comment by rolfmorel** [comment]
I agree that macht should use a default save path according to the [XDG base dir spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).
Without any commandline flags the game should just use this default file to save the game's state on `q`uit. The user should be able to just resume this previous game by using a single simple option which should be either `-c`/`--continue` or `-r`/`--resume`. I have yet to decide which is most fitting.

There should also be a possibility to specify you want to save the game's state to another file, for example if you aren't playing the default 4x4 grid or are using a non-default base.
When the user `q`uits this game it saves the state to this the new file. The problem is if you overload the continue option with a optional file to save to/resume from you can not start a new game using a file which already has a save state in it, it would just load that state.

One possible solution is to say that when the user uses the continue option **and** specifies a board size and/or base number it start a new game and will overwrite the old save file.

As for getting the score from the tiles on the board: Yes, in theory, you could calculate the score from the current values on the board if you knew the base value. The problem is that the game randomly spawns a 4 (exponent=2) tile one tenths of the time according to the behavior of the original 2048. So without utilizing any extra state I do not believe it is possible.

And the user would probably expect to be able to continue with the previous base number in which case you are already recording a different type which wouldn't fit in CSV records model.

Which leads leads me to a solution with JSON or YAML or other equivalent. With these you can keep track of the score and base number separately and save the tiles as a position and exponent.
And, for example with YAML, you can use the same "key" names as the argument names used by the constructor of `Grid.__init__` and arguments of `.spawn_tile()`:

```
score: 20
base: 2
rows: 4
columns: 4

tiles:
  - row: 1
    column: 3
    exponent: 1
  - row: 2
    column: 3
    exponent: 2
  - row: 3
    column: 2
    exponent: 1
  - row: 3
    column: 3
    exponent: 3
```

EDIT: and what should also be a consideration is that with a more involved storage format it would be easier to be future compatible, would there ever be need to store more state.

**Comment by HalosGhost** [comment]
That sounds like a perfect solution!

**Comment by rolfmorel** [comment]
Thanks.

Then I know what I will have to work on next.

**Comment by rolfmorel** [comment]
@HalosGhost 
I implemented the save/resume feature. The patch mostly implements what is outlined above: it uses the `-r`/`--resume` command line option and JSON is used, instead of YAML, as storage format.

I would appreciate it if you could test it. If everything works I will push a new release to pypi.

**Comment by HalosGhost** [comment]
@polyphemus, well-done on the quick implementation. Quick tests reveal one issue that (whether or not you want to actually offer a default solution for) should be handled more gracefully. If I specify a file that does not exist, one is created, which is just fine. However, if I specify a file in a folder that does not exist (e.g., `$XDG_CONFIG_HOME/macht/save.state`), `macht` fails:

```
Traceback (most recent call last):
  File "/usr/bin/macht", line 9, in <module>
    load_entry_point('macht==0.1.2', 'console_scripts', 'macht')()
  File "/usr/lib/python3.4/site-packages/macht/term/main.py", line 134, in main
    save.write_to_file(score, grids, filename=resume or None)
  File "/usr/lib/python3.4/site-packages/macht/save.py", line 31, in write_to_file
    with open(filename, 'w') as save_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/halosghost/.config/macht/save.state'
```

Admittedly, this error explicitly says this is because the directory does not exist, but having a traceback in a fairly plausible case seems like bad practice to me.

A simple check to see if the directory exists (or even just error handling in case it doesn't) would be fine.

The actual behavior of the save state works great; it remembers history perfectly! :+1:

**Comment by rolfmorel** [comment]
Thank you for the feedback.

Great that everything else works and for the issue you found I have pushed a patch which just creates leading directories that do not exist.
I prefer that commandline programs just create these missing directories and that if you feed such a program wrong filenames that it is your own responsibility to clean it up.

> Admittedly, this error explicitly says this is because the directory does not exist, but having a traceback in a fairly plausible case seems like bad practice to me.

Would I have kept the old behaviour, I would indeed have preferred a nicer error message.
